version: 0.2

env:
  variables:
    CHECKOV_VERSION: "3.2.0"
    TEMPLATE_FILE: "template.yml"
    SOURCE_BUCKET: "radha-test-s3-bucket"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "===> Installing Checkov..."
      - pip install checkov==$CHECKOV_VERSION --break-system-packages
      - checkov --version

  pre_build:
    commands:
      - echo "===> Checking files exist..."
      - test -f template.yml || (echo "ERROR template.yml not found" && exit 1)
      - test -f custom-rules/check_single_s3.py || (echo "ERROR custom rule not found" && exit 1)
      - echo "===> All files found"
      - ls -la custom-rules/
      - mkdir -p artifacts

  build:
    commands:
      - echo "===> Running Checkov on $TEMPLATE_FILE..."
      - checkov --config-file .checkov.yaml --file $TEMPLATE_FILE --external-checks-dir ./custom-rules --output cli > artifacts/checkov_result.txt 2>&1 || true
      - echo "===> Checkov scan complete"

artifacts:
  base-directory: artifacts
  files:
    - '**/*'