version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.12
  pre_build:
    on-failure: ABORT
    commands:
      - mkdir -p artifacts
      # Calculate hash of layer content
      - |
        (cd infra_automation/common_modules/ && zip -rq - .) > layer_content.zip
        LAYER_HASH=$(openssl dgst -sha256 -r layer_content.zip | awk '{print $1}')
        echo "Layer hash: $LAYER_HASH"
        echo "LAYER_HASH=$LAYER_HASH" >> env.properties
      - |
        (cd infra_automation/numpy_modules/ && zip -rq - .) > numpy_layer_content.zip
        NUMPY_LAYER_HASH=$(openssl dgst -sha256 -r numpy_layer_content.zip | awk '{print $1}')
        echo "numpy layer hash: $NUMPY_LAYER_HASH"
        echo "NUMPY_LAYER_HASH=$NUMPY_LAYER_HASH" >> env.properties
      - |
        (cd infra_automation/pandas_modules/ && zip -rq - .) > pandas_layer_content.zip
        PANDAS_LAYER_HASH=$(openssl dgst -sha256 -r pandas_layer_content.zip | awk '{print $1}')
        echo "pandas layer hash: $PANDAS_LAYER_HASH"
        echo "PANDAS_LAYER_HASH=$PANDAS_LAYER_HASH" >> env.properties
      - cat env.properties > env.txt
  build:
    on-failure: ABORT
    commands:
      - echo "Build script execution."
  post_build:
    on-failure: ABORT
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket $BUILD_OUTPUT_BUCKET --s3-prefix $BUILD_OUTPUT_PREFIX --output-template-file artifacts/packaged.yaml --parameter-overrides file://env.txt
artifacts:
  type: zip
  files:
    - 'artifacts/*/'